#ifndef _GNURADIO_H_
#define _GNURADIO_H_

#include <gnuradio/analog/agc2_cc.h>
#include <gnuradio/analog/agc2_ff.h>
#include <gnuradio/analog/agc_ff.h>
#include <gnuradio/analog/frequency_modulator_fc.h>
#include <gnuradio/analog/noise_source_f.h>
#include <gnuradio/analog/noise_source_c.h>
#include <gnuradio/analog/pll_refout_cc.h>
#include <gnuradio/analog/probe_avg_mag_sqrd_c.h>
#include <gnuradio/analog/quadrature_demod_cf.h>
#include <gnuradio/analog/sig_source_c.h>
#include <gnuradio/analog/sig_source_f.h>
#include <gnuradio/analog/simple_squelch_cc.h>
#include <gnuradio/audio/sink.h>
#include <gnuradio/audio/source.h>
#include <gnuradio/blocks/add_cc.h>
#include <gnuradio/blocks/add_const_cc.h>
#include <gnuradio/blocks/add_const_ff.h>
#include <gnuradio/blocks/add_ff.h>
#include <gnuradio/blocks/complex_to_float.h>
#include <gnuradio/blocks/complex_to_imag.h>
#include <gnuradio/blocks/complex_to_mag.h>
#include <gnuradio/blocks/complex_to_real.h>
#include <gnuradio/blocks/copy.h>
#include <gnuradio/blocks/file_sink.h>
#include <gnuradio/blocks/file_source.h>
#include <gnuradio/blocks/float_to_complex.h>
#include <gnuradio/blocks/float_to_short.h>
#include <gnuradio/blocks/keep_one_in_n.h>
#include <gnuradio/blocks/message_sink.h>
#include <gnuradio/blocks/message_source.h>
#include <gnuradio/blocks/moving_average_cc.h>
#include <gnuradio/blocks/multiply_cc.h>
#include <gnuradio/blocks/multiply_const_cc.h>
#include <gnuradio/blocks/multiply_const_ff.h>
#include <gnuradio/blocks/multiply_ff.h>
#include <gnuradio/blocks/null_sink.h>
#include <gnuradio/blocks/null_source.h>
#include <gnuradio/blocks/short_to_float.h>
#include <gnuradio/blocks/stream_to_vector.h>
#include <gnuradio/blocks/sub_ff.h>
#include <gnuradio/blocks/throttle.h>
#include <gnuradio/blocks/vector_sink_f.h>
#include <gnuradio/digital/costas_loop_cc.h>
#include <gnuradio/fft/fft_vcc.h>
#include <gnuradio/filter/dc_blocker_ff.h>
#include <gnuradio/filter/fir_filter_ccc.h>
#include <gnuradio/filter/fir_filter_ccf.h>
#include <gnuradio/filter/fir_filter_fcc.h>
#include <gnuradio/filter/fir_filter_fff.h>
#include <gnuradio/filter/firdes.h>
#include <gnuradio/filter/freq_xlating_fir_filter_ccc.h>
#include <gnuradio/filter/freq_xlating_fir_filter_ccf.h>
#include <gnuradio/filter/freq_xlating_fir_filter_fcf.h>
#include <gnuradio/filter/rational_resampler_base_ccf.h>
#include <gnuradio/filter/rational_resampler_base_fff.h>
#include <gnuradio/top_block.h>
#include <gnuradio/vocoder/alaw_decode_bs.h>
#include <gnuradio/vocoder/alaw_encode_sb.h>
#include <gnuradio/vocoder/ulaw_decode_bs.h>
#include <gnuradio/vocoder/ulaw_encode_sb.h>
#include <hiqsdr/sink.h>
#include <hiqsdr/source.h>
//#include <gnuradio/noise_source_c.h>

#endif
